### ISSUE TITLE
Enlarged Secure checkout logo

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Kerly-Pierre--Store-dev---31-March-2022#1]
The speed store is having enlarged secure checkout logo.
https://gxxmg87s7g9frcod-58430554266.shopifypreview.com/pages/secure-checkout
![image](https://user-images.githubusercontent.com/97726944/172371291-058ee437-8c44-43d3-8f33-cb6ec3b870c6.png)

**Comment by devShivDuttChauhan** [comment]
I have fixed this problem.
![image](https://user-images.githubusercontent.com/103488177/172532839-6c9b5df3-4219-4c1b-81cd-6ff7c7d1ba8a.png)
