### ISSUE TITLE
Enlarged mail icon in contact page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Kerly-Pierre--Store-dev---31-March-2022#2]
The contact page mail icon is different in live & preview.
https://gxxmg87s7g9frcod-58430554266.shopifypreview.com/pages/contact-us
![image](https://user-images.githubusercontent.com/97726944/172371547-da861165-b415-4a6c-9daf-ccff352ed7d3.png)

**Comment by devShivDuttChauhan** [comment]
"Enlarged mail icon" problem comming from Designer kindly Inform him sir.
